public static class Enums
{
    public enum SCENE_TYPE { MAIN_MENU, IN_GAME, ENUM_SIZE }

    public enum GAME_SETTING_TYPE { BGM_VOLUMN, SFX_VOLUMN }

    public enum STAT_TYPE { DMG, MHP, NHP, MVSPD, ATKSPD, JUMP_POWER, MSTAMINA, NSTAMINA }

    public enum ITEM_TYPE { WEAPON, ARMOR, ACCESSORY, CONSUMABLE }
    public enum ITEM_GRADE { NORMAL, RARE, EPIC, LEGENDARY }
}